name: End-to-end tests
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  cypress-run:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          start: npm run develop:test
          wait-on: http://localhost:3030
